name: tenpydoc
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - cython>=0.29
  - bottleneck
  - pip
  - setuptools>=68.0.0
  - h5py
  - pyyaml
  - sphinx=6.2.1
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex!=2.6
  - matplotlib
  - ipykernel
  - nbsphinx
  - graphviz
  - pandoc
  - sphinx-copybutton
