name: code_coverage

# Note: the pytest action assumes that this workflow runs the full pytest
#       suite for the most recent python version.

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge --recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools build
        python -m pip install --upgrade pytest
        python -m pip install --upgrade coverage
    - name: Build and install tenpy
      run: |
        python -m build .
        python -m pip install .
    - name: Run pytest with coverage
      # configuration in pyproject.toml
      run: |
        python -m coverage run -m pytest
        python -m coverage report -m --skip-covered
        python -m coverage json
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.json
        if-no-files-found: error
